name: Deploy Static Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install -g html-minifier-terser
    
        - name: Replace environment variables
        run: |
          echo "=== DEBUGGING FILE REPLACEMENT ==="
          echo "Current directory: $(pwd)"
          echo "Files in root:"
          ls -la
          echo "Looking for index.html..."
          
          if [ -f "index.html" ]; then
            echo "✓ Found index.html"
            echo "Before replacement:"
            grep -n "YOUR_" index.html || echo "No YOUR_ placeholders found"
            
            # Do replacements
            sed -i "s/YOUR_SERVICE_ID/${{ secrets.EMAILJS_SERVICE_ID }}/g" index.html
            sed -i "s/YOUR_TEMPLATE_ID/${{ secrets.EMAILJS_TEMPLATE_ID }}/g" index.html
            
            echo "After replacement:"
            grep -n "YOUR_" index.html || echo "✓ All placeholders replaced"
          else
            echo "✗ index.html NOT FOUND in root directory"
            echo "Available HTML files:"
            find . -name "*.html"
          fi
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: easydoesit.ca
        exclude_assets: '.github,README.md,*.md'