name: Deploy Static Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install -g html-minifier-terser
    
    - name: Replace environment variables
      run: |
        # Show current directory and file structure
        echo "Current directory: $(pwd)"
        echo "All files in repository:"
        find . -type f -name "*.html"
        
        # Set variables based on event type
        if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "Production deployment - using secrets"
          SERVICE_ID="${{ secrets.EMAILJS_SERVICE_ID }}"
          TEMPLATE_ID="${{ secrets.EMAILJS_TEMPLATE_ID }}"
        else
          echo "Pull request or non-main branch - using placeholder values"
          SERVICE_ID="test_service_id"
          TEMPLATE_ID="test_template_id"
        fi
        
        # Replace in the root index.html specifically
        if [ -f "./index.html" ]; then
          echo "Found index.html in root, replacing variables..."
          sed -i "s/YOUR_SERVICE_ID/$SERVICE_ID/g" ./index.html  
          sed -i "s/YOUR_TEMPLATE_ID/$TEMPLATE_ID/g" ./index.html
          echo "Replacement completed for root index.html"
        else
          echo "index.html not found in root, searching subdirectories..."
          find . -name "index.html" -type f -exec sed -i "s/YOUR_SERVICE_ID/$SERVICE_ID/g" {} \;
          find . -name "index.html" -type f -exec sed -i "s/YOUR_TEMPLATE_ID/$TEMPLATE_ID/g" {} \;
          echo "Replacement completed for all index.html files"
        fi
        
        # Show what was actually replaced (without revealing secrets)
        echo "Files that were processed:"
        find . -name "*.html" -exec echo "Processing: {}" \;
        
        # Verify replacements worked
        echo "Checking for remaining placeholders:"
        if find . -name "*.html" -exec grep -l "YOUR_.*_ID\|YOUR_PUBLIC_KEY" {} \; 2>/dev/null; then
          echo "⚠️  Warning: Some placeholders may not have been replaced"
        else
          echo "✓ All placeholders appear to be replaced successfully"
        fi
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: www.easydoesit.ca
        exclude_assets: '.github,README.md,*.md'